language: csharp
solution: portfolio.sln

before_install:
- sudo apt-get -qq update

script:
- xbuild /p:Configuration=Release portfolio.sln
- mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./bin/Release/portfolio.exe